### ISSUE TITLE
Drink module

### ISSUE THREAD

**Issue by asmundb** [luc-girod/GeoUiOJan201_day3_2#4] opened 2021-01-13 10:18 UTC
I think it would be nice to add drinks that goes with tacos.

**Comment by kjetilaas** [comment] 2021-01-13 10:19
This is basically the same as issue #2. Could we work together on this? @asmundb

**Comment by luc-girod** [comment] 2021-01-13 10:19
Issue is a duplicate of #2

**Closed as completed by luc-girod** 2021-01-13 10:19 UTC
